name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) print the tree once (optional; remove after verifying)
      - name: Dump repository tree
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          ls -R .

      # 3) set up Docker Buildx (needed for multi‑arch or buildx features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) ensure `docker compose` is on the PATH
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      # 5) spin up your stack (will pick up docker‑compose.yml at repo root)
      - name: Bring up services
        run: docker compose up -d

      # 6) copy your env file
      - name: Copy .env.example → .env
        run: cp .env.example .env

      # 7) install your Node dependencies
      - name: Install dependencies
        run: npm ci

      # 8) run your integration script
      - name: Run integration tests
        run: ./scripts/run-integration.sh

      # 9) always tear down your containers
      - name: Tear down services
        if: always()
        run: docker compose down
