name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        # installs the latest Compose binary if missing :contentReference[oaicite:0]{index=0}

      - name: Docker Compose up
        run: docker compose -f 1-integ-tests/docker-compose.yml up -d

      - name: Copy .env.example to .env
        run: cp 1-integ-tests/.env.example 1-integ-tests/.env

      - name: Install dependencies
        run: cd 1-integ-tests && npm install

      - name: Run integration script
        run: cd 1-integ-tests && npm run test-integration

      - name: Tear down Compose services
        if: always()
        run: docker compose -f 1-integ-tests/docker-compose.yml down
