name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Treat '1-integ-tests' as our project root for every `run:` step
    defaults:
      run:
        working-directory: 1-integ-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Bring up services
        run: |
          docker compose up -d

      - name: Copy environment file
        run: cp .env.example .env

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm run test-integration

      - name: Tear down services
        if: always()
        run: docker compose down
